### ISSUE TITLE
lrpinfo() error

### ISSUE THREAD

**Issue by Leonmmcoset** [Leonmmcoset/leonranp#2]
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    lrpinfo()
  File "C:\Users\leonm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\leonranp\__init__.py", line 176, in lrpinfo
    import InfoWindow
ModuleNotFoundError: No module named 'InfoWindow'

**Comment by Leonmmcoset** [comment]
Well,sorry
I didn't study very well on mult-python file :(
I should study all about this

**Comment by Leonmmcoset** [comment]
Fix in 0.1.3
